		"[...] updates APT.""\n"
		"[] sudo dpkg --configure -a""\n"
		"[] sudo apt-get clean -y""\n"
		"[] sudo apt-get install --reinstall -f -y""\n"
		"[] sudo apt-get update -y""\n"
		"[] sudo apt-get install --reinstall apt -y""\n"
		"[] sudo apt-get install --reinstall software-properties-common -y""\n"
		"[] sudo apt-get clean -y""\n"
		"[] sudo apt-get autoclean -y""\n"
		"[] sudo apt-get update -y""\n"
		"[] switches path to '~'.""\n"
